# College Major Salary Analysis

In [ ]:
import pandas as pd

In [2]:
df=pd.read_csv("salaries_by_college_major.csv")

In [3]:
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

In [4]:
df.shape

(51, 6)

In [5]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='str')

In [6]:
df.isna().sum()

Undergraduate Major                  0
Starting Median Salary               1
Mid-Career Median Salary             1
Mid-Career 10th Percentile Salary    1
Mid-Career 90th Percentile Salary    1
Group                                1
dtype: int64

In [7]:
df=df.dropna()

In [8]:
df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

## Finding the highest sarting salary

### Technique 1

In [9]:
df['Starting Median Salary'].max()

np.float64(74300.0)

In [10]:
df[df['Starting Median Salary']==df['Starting Median Salary'].max()]

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM

### Technique 2

In [11]:
df['Starting Median Salary'].idxmax()

43

In [12]:
df['Undergraduate Major'].loc[43]

'Physician Assistant'

In [13]:
df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

## Finding lowest starting salary

In [14]:
df['Starting Median Salary'].min()

np.float64(34000.0)

In [15]:
df[df['Starting Median Salary']==df['Starting Median Salary'].min()]

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [16]:
df[df['Starting Median Salary']==df['Starting Median Salary'].min()]['Undergraduate Major']

49    Spanish
Name: Undergraduate Major, dtype: str

In [17]:
df['Starting Median Salary'].idxmin()

49

In [18]:
df.loc[49]

Undergraduate Major                  Spanish
Starting Median Salary               34000.0
Mid-Career Median Salary             53100.0
Mid-Career 10th Percentile Salary    31000.0
Mid-Career 90th Percentile Salary    96400.0
Group                                   HASS
Name: 49, dtype: object

In [19]:
df['Undergraduate Major'].loc[49]

'Spanish'

### Finding college major with lowest mid-career salary

In [20]:
df['Mid-Career Median Salary'].idxmin()

18

In [21]:
df['Undergraduate Major'].loc[18]

'Education'

In [22]:
df.loc[18]

Undergraduate Major                  Education
Starting Median Salary                 34900.0
Mid-Career Median Salary               52000.0
Mid-Career 10th Percentile Salary      29300.0
Mid-Career 90th Percentile Salary     102000.0
Group                                     HASS
Name: 18, dtype: object

### Finding college majors with highest mid career salary

In [23]:
df['Mid-Career Median Salary'].max()

np.float64(107000.0)

In [24]:
df[df['Mid-Career Median Salary']==df['Mid-Career Median Salary'].max()]

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM

In [25]:
df['Mid-Career 90th Percentile Salary']-df['Mid-Career 10th Percentile Salary']

0     109800.0
1      96700.0
2     113700.0
3     104200.0
4      85400.0
5      96200.0
6      98100.0
7     108200.0
8     122100.0
9     102700.0
10     84600.0
11    105500.0
12     95900.0
13     98000.0
14    114700.0
15     74800.0
16    116300.0
17    159400.0
18     72700.0
19     98700.0
20     99600.0
21    102100.0
22    147800.0
23     70000.0
24     92000.0
25    111000.0
26     76000.0
27     66400.0
28    112000.0
29     88500.0
30    115900.0
31     84500.0
32     71300.0
33    118800.0
34    106600.0
35    100700.0
36    132900.0
37    137800.0
38     99300.0
39    107300.0
40     50700.0
41     65300.0
42    132500.0
43     57600.0
44    122000.0
45    126800.0
46     95400.0
47     66700.0
48     87300.0
49     65400.0
dtype: float64

In [26]:
df['Spread']=df['Mid-Career 90th Percentile Salary']-df['Mid-Career 10th Percentile Salary']

In [27]:
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,Spread
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business,109800.0
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM,96700.0
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business,113700.0
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS,104200.0
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business,85400.0

In [28]:
df['Spread'].min()

np.float64(50700.0)

In [29]:
df[df['Spread']==df['Spread'].min()]

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,Spread
40,Nursing,54200.0,67000.0,47600.0,98300.0,Business,50700.0

In [30]:
df['Spread'].sort_values()

40     50700.0
43     57600.0
41     65300.0
49     65400.0
27     66400.0
47     66700.0
23     70000.0
32     71300.0
18     72700.0
15     74800.0
26     76000.0
31     84500.0
10     84600.0
4      85400.0
48     87300.0
29     88500.0
24     92000.0
46     95400.0
12     95900.0
5      96200.0
1      96700.0
13     98000.0
6      98100.0
19     98700.0
38     99300.0
20     99600.0
35    100700.0
21    102100.0
9     102700.0
3     104200.0
11    105500.0
34    106600.0
39    107300.0
7     108200.0
0     109800.0
25    111000.0
28    112000.0
2     113700.0
14    114700.0
30    115900.0
16    116300.0
33    118800.0
44    122000.0
8     122100.0
45    126800.0
42    132500.0
36    132900.0
37    137800.0
22    147800.0
17    159400.0
Name: Spread, dtype: float64

In [31]:
df['Spread'].sort_values(ascending=False).head(5)

17    159400.0
22    147800.0
37    137800.0
36    132900.0
42    132500.0
Name: Spread, dtype: float64

In [32]:
df.sort_values(by='Mid-Career 90th Percentile Salary',ascending=False).head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,Spread
17,Economics,50100.0,98600.0,50600.0,210000.0,Business,159400.0
22,Finance,47900.0,88300.0,47200.0,195000.0,Business,147800.0
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM,122100.0
37,Math,45400.0,92400.0,45200.0,183000.0,STEM,137800.0
44,Physics,50300.0,97300.0,56000.0,178000.0,STEM,122000.0

### Finding majors with the highest potential

In [33]:
df.sort_values(by="Spread",ascending=False).head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,Spread
17,Economics,50100.0,98600.0,50600.0,210000.0,Business,159400.0
22,Finance,47900.0,88300.0,47200.0,195000.0,Business,147800.0
37,Math,45400.0,92400.0,45200.0,183000.0,STEM,137800.0
36,Marketing,40800.0,79600.0,42100.0,175000.0,Business,132900.0
42,Philosophy,39900.0,81200.0,35500.0,168000.0,HASS,132500.0

In [34]:
df.sort_values(by="Spread",ascending=False).head()[['Undergraduate Major','Spread']]

   Undergraduate Major    Spread
17           Economics  159400.0
22             Finance  147800.0
37                Math  137800.0
36           Marketing  132900.0
42          Philosophy  132500.0

In [35]:
df.sort_values(by='Mid-Career Median Salary',ascending=False).head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group,Spread
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM,122100.0
12,Computer Engineering,61400.0,105000.0,66100.0,162000.0,STEM,95900.0
19,Electrical Engineering,60900.0,103000.0,69300.0,168000.0,STEM,98700.0
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM,96700.0
17,Economics,50100.0,98600.0,50600.0,210000.0,Business,159400.0

In [36]:
df.sort_values(by='Mid-Career Median Salary',ascending=False).head()[['Undergraduate Major','Mid-Career Median Salary']]

       Undergraduate Major  Mid-Career Median Salary
8     Chemical Engineering                  107000.0
12    Computer Engineering                  105000.0
19  Electrical Engineering                  103000.0
1    Aerospace Engineering                  101000.0
17               Economics                   98600.0

In [37]:
df.groupby('Group').count()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Spread
Group,,,,,,
Business,12,12,12,12,12,12
HASS,22,22,22,22,22,22
STEM,16,16,16,16,16,16

In [38]:
df.groupby('Group').mean(numeric_only=True)

,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Spread
Group,,,,,
Business,44633.333333,75083.333333,43566.666667,147525.000000,103958.333333
HASS,37186.363636,62968.181818,34145.454545,129363.636364,95218.181818
STEM,53862.500000,90812.500000,56025.000000,157625.000000,101600.000000